header:
  version: 14

machine: qemuarm64
distro: microrun
target: minimal-init-image

repos:
  meta-custom:
  poky:
    url: https://github.com/yoctoproject/poky.git
    path: /build/kas/poky
    commit: 7e081bd98fdc5435e850d1df79a5e0f1e30293d0
    layers:
      meta:
      meta-poky: