header:
  version: 14
  includes:
    - base.yml

local_conf_header:
  meta-custom: |
    BB_HASHSERVE_UPSTREAM = "wss://hashserv.yoctoproject.org/ws"
    SSTATE_MIRRORS ?= "file://.* http://cdn.jsdelivr.net/yocto/sstate/all/PATH;downloadfilename=PATH"
    BB_HASHSERVE = "auto"
    BB_SIGNATURE_HANDLER = "OEEquivHash"

    INHERIT += "externalsrc"
    EXTERNALSRC:pn-init-go = "/builder"
    EXTERNALSRC_BUILD:pn-init-go = "/builder"